_BASE_: "../Base-RCNN-FPN.yaml"

MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"  # 使用 ResNet-50 的预训练权重
  MASK_ON: False  # 因为我们不进行实例分割，所以不需要 mask 分支
  RESNETS:
    DEPTH: 50  # 更改骨干网络深度为 50 层

  # 更新 ROI_HEADS 配置以适配我们的任务
  ROI_HEADS:
    NUM_CLASSES: 15  # 你的数据集中有 3 个类别 + 1 背景

SOLVER:
  IMS_PER_BATCH: 16  # 或更高，取决于实际显存使用情况
  BASE_LR: 0.005  # 根据批量大小调整
  STEPS: (60000, 80000)  # 这些是学习率衰减的步骤，需要根据 MAX_ITER 来调整
  MAX_ITER: 100000  # 最大迭代次数，同样根据你的数据集大小和复杂度调整

DATASETS:
  TRAIN: ("fish_train",)  # 使用你注册的训练数据集的名字
  TEST: ("fish_val",)  # 使用你注册的验证数据集的名字
